### ISSUE TITLE
Confusing naming scheme

### ISSUE THREAD

**Issue by djarek** [LeonineKing1199/f3#3]
https://github.com/LeonineKing1199/f3/blob/f0dd6e2d2fc97b4e5e9e09fc03752ed1b1e3b06d/include/foxy/detail/timed_op_wrapper.hpp#L33-L35

Using `_` in function argument names may lead to confusion for readers.

**Comment by LeonineKing1199** [comment]
This has been addressed with: https://github.com/LeonineKing1199/f3/commit/62cdbef20c29b7c5f4e43e07789bb3496eb04f4e#diff-4df99d8d31195f04ce24307615cab9d8R40
