### ISSUE TITLE
foxy can't read post request in foxy server example

### ISSUE THREAD

**Issue by uikino** [LeonineKing1199/f3#36]
I use this freamwork to write an httpd, and I find that when I use postman to test my httpd,run until  calling `yield server.async_read(f.request, std::move(self));` will directly return. then output the Encountered error in the console when reading in the request!
This is postman test example:
`http://127.0.0.1:1337/python/add_task/`
Environment.
`boost 1.72.0 and patch boost office patch`
`g++ 9.3.0`

I'm sorry, my English is very poor. I hope you understand.

**Comment by cmazakas** [comment]
Thank you for filing an issue!

I'll take a look when I get home from work tonight.

**Comment by cmazakas** [comment]
Ah, I know what's likely to be wrong.

If you copied the example, my guess is that you're not using the correct Beast body type in the `http::request`. As you can see here: https://github.com/LeonineKing1199/foxy/blob/develop/examples/server/main.cpp#L39

We use the `http::empty_body`. If you POST a message containing a body to this server, `async_read` will fail with an `unexpected_body` error. To fix this, you should change the code to:
```cpp

  struct frame
  {
    http::request<http::string_body>   request;
    http::response<http::string_body> response;
  };
```

This will allow you to read in the message body that Postman is sending.

**Comment by uikino** [comment]
Thanks for the reply, the problem has been solved perfectly!
