### ISSUE TITLE
issues compiling with latest boost v1.74

### ISSUE THREAD

**Issue by aboseley** [LeonineKing1199/f3#37]
This looks like a really great library, but I'm having some issues getting it to build with the latest boost version.

Boost v1.74 fails - https://travis-ci.com/github/aboseley/foxy/builds/204997021
Boost v1.71 succeds - https://travis-ci.com/github/aboseley/foxy/builds/205001794

**Comment by cmazakas** [comment]
That actually makes good sense... Asio moves fast and likes to break things and I haven't touched the library in a little while now.

I'll start looking into this. If anything, this seems like it's because of Asio's refactoring to match the Executors TS. I'll look into seeing if I can support pre-1.74 and post-1.74 at the same time otherwise I'll probably just update the minimum required version of Boost.

**Comment by cmazakas** [comment]
Alright, I looked into it.

It seems like upgrading to 1.74 is going to be somewhat large refactor. I've been busy with other open source projects and nowadays, free time is kind of precious.

I likely won't be addressing this any time soon but I will accept PRs.

Things that need to be addressed:
* Asio changed default Executor for I/O objects to be `any_io_executor` so `executor` needs to be replaced
* `beast::test::stream` moved `lowest_layer_type` and associated member functions so the tests no longer pass

**Comment by cmazakas** [comment]
Update:

Beast devs are looking into un-deprecating the `test::stream`'s `lowest_layer_type` so I think Foxy can be updated for the latest Boost release after 1.74.

Once 1.75 beta is on the way, I'll make the update and then we'll get Foxy working with modern Boost.

**Comment by aboseley** [comment]
This branch compiles locally with 1.75, and the unit tests pass
https://github.com/aboseley/foxy/tree/issue37-compile-with-boost175

Thou there's probably a bit more to do to get the ci happy

**Comment by cmazakas** [comment]
Hmm, now that we've updated Foxy to compile with 1.75 and set that as its minimum version, can we go ahead and close this issue?
